### PR TITLE
Make explosions visible

### LINKED ISSUE #508: ExplosionMessage is only sent to players that get damaged
Hi,

Did some more testing. The explosion particles are not visible when you are not in the range of the explosion.
How to reproduce:
1) Place a tnt block
2) ignite it
3) Go a few block (20 or so) away

In vanilla, the explosion is visible from far away.

In glowstone, the explosion is not visible.
However, when you get damaged by the explosion, you will see the particles.

Version:
`
This server is running Glowstone version 2017.6.1-SNAPSHOT.0826543-MC1.12 (Implementing API version 1.12-R0.1-SNAPSHOT)
`

best regards
Postremus

### PR DESCRIPTION
**Pull request by Postremus**
After some testing in vanilla, I figured out that explosions are visible in a range of 64 blocks.  

Also, separate damage and visibility calculations.
closes #508

### CODE REVIEW

File: src/main/java/net/glowstone/Explosion.java [hunk 1]
```diff
@@ -255,7 +260,6 @@ private void setBlockOnFire(GlowBlock block) {
             entity.damage(damage, source, damageCause);
 
             if (entity instanceof GlowPlayer) {
```
Comment (mastercoms) [inline src/main/java/net/glowstone/Explosion.java]: Merge the two if statements, please

**Review by mastercoms — CHANGES_REQUESTED** [review]

**Review by gdude2002 — APPROVED** [review]
:+1:

File: src/main/java/net/glowstone/Explosion.java (hunk 1 above)
Comment (Postremus) [inline src/main/java/net/glowstone/Explosion.java]: Will do.
Actually, you pointed another possible error with explosions out.
Flying players will, at least in paper 1.10, take damage from explosions.
However, this will need more testing -> another pr.

**Review by mastercoms — APPROVED** [review]

**Comment by gdude2002** [comment]
Thanks for the contribution!
