### PR TITLE
Fixes crafting

### LINKED ISSUE #137: Crafting Bug
When I went into the inventory 2 by 2 crafting grid to make some planks, I placed the wood and it stayed for a fraction of a second, then disappeared. I exited the inventory and the logs flew out of me and I picked them up. This bug also happens in the regular crafting table.

### PR DESCRIPTION
**Pull request by bluekelp**
1.8.9 client (vanilla) glitched horribly for me when I tried to craft basic items (LOG -> WOOD -> STICKS).

Fixed the glitches, enhanced inventory code to not lose (some) unused inputs when closing crafting window (if using a crafting table), fixed an item dup bug, and refactored code a tiny bit.

---

EDIT by mastercoms:

fixes #137 and #101

### CODE REVIEW

**Comment by mastercoms** [comment]
I can't right click and drag to place items in the crafting box.

File: src/main/java/net/glowstone/net/handler/play/inv/WindowClickHandler.java [hunk 1]
```diff
@@ -42,7 +42,7 @@ private boolean process(final GlowPlayer player, final WindowClickMessage messag
         final InventoryView view = player.getOpenInventory();
         final GlowInventory top = (GlowInventory) view.getTopInventory();
         final GlowInventory bottom = (GlowInventory) view.getBottomInventory();
-        final ItemStack slotItem = view.getItem(viewSlot);
+        final ItemStack slotItem = message.getItem();
```
Comment (mastercoms) [inline src/main/java/net/glowstone/net/handler/play/inv/WindowClickHandler.java]: Could you explain the reason for this change?

**Comment by mastercoms** [comment]
I did a bit of regression testing, and it seems like https://github.com/GlowstonePlusPlus/GlowstonePlusPlus/commit/6c7c822fda3653d96055467e7dac0a163412c2a4 was the last commit where everything worked. I don't remember changing anything related to the inventory after that.

File: src/main/java/net/glowstone/entity/GlowHumanEntity.java [hunk 2]
```diff
@@ -390,14 +390,36 @@ public void closeInventory() {
...
+    private void dropUnusedInputs() {
+        for (int i = 0; i <= getTopInventory().getSlots().size(); i++) {
+            final ItemStack itemStack = getOpenInventory().getItem(i);
+            if (itemStack == null || itemStack.getAmount() == 0 || itemStack.getType() == Material.AIR) {
+                continue;
+            }
+
+            if (isCraftingInputSlot(i)) {
+                drop(itemStack);
+                getOpenInventory().setItem(i, null);
```
Comment (mastercoms) [inline src/main/java/net/glowstone/entity/GlowHumanEntity.java]: CraftBukkit's expected behavior is Material.AIRx0

**Comment by mastercoms** [comment]
I have fixed the crafting issues in https://github.com/GlowstonePlusPlus/GlowstonePlusPlus/commit/0be6bc0a5ec62dbf8aa967d831c7a1c47e6536fc

File: src/main/java/net/glowstone/net/handler/play/inv/WindowClickHandler.java (hunk 1 above)
Comment (bluekelp) [inline src/main/java/net/glowstone/net/handler/play/inv/WindowClickHandler.java]: the view.getItem(viewSlot) was null, caused the action in WindowLogic something or other to return NOTHING - nerfing most crafting actions/clicks. maybe my change masks a more serious issue elsewhere?

Comment (mastercoms) [inline src/main/java/net/glowstone/net/handler/play/inv/WindowClickHandler.java]: Yeah, and the underlying issue was fixed in https://github.com/GlowstonePlusPlus/GlowstonePlusPlus/commit/0be6bc0a5ec62dbf8aa967d831c7a1c47e6536fc

I had followed a plugin stacktrace incorrectly, as I was trying to fix a NullPointerException error with many plugins that deal with items. I discovered it was because these plugins were expecting air, not null, probably because of a Bukkit rule. So I "fixed" getItem, instead of fixing the true culprit, getItemInHand, which was fixed in above mentioned commit. The previous "fix" is what fixed a mostly stable crafting.

And your contribution probably made it perfect.
