### PR TITLE
Fixes Guardian/ElderGuardian API #968

### LINKED ISSUE #968: Implementation of Guardian/ElderGuardian API
### *Disclaimer for new contributors*
Glowstone is an open-source project under the MIT license. In addition, we have a [Contributors License Agreement](https://glowstone.net/cla) which includes restrictions on the source of contributions (e.g. decompiled code from Mojang, Spigot, etc.). You will be asked to sign the CLA when submitting your first Pull Request.

### Task
In a previous API update, the [Guardian]() API was split into the Guardian and [ElderGuardian]() interfaces. The implementations ([GlowGuardian](https://github.com/GlowstoneMC/Glowstone/blob/dev/src/main/java/net/glowstone/entity/monster/GlowGuardian.java), [GlowElderGuardian](https://github.com/GlowstoneMC/Glowstone/blob/dev/src/main/java/net/glowstone/entity/monster/GlowElderGuardian.java)) need to reflect these changes.

### Details

 * In GlowGuardian:
   * Make `isElder()` return `false`.
   * Make `setElder(boolean)`...:
     * summon a new `GlowElderGuardian` at the same position and remove the current entity, **only if** `isElder()` return `false` and the parameter is `true`.
     * summon a new `GlowGuardian` at the same position and remove the current entity, **only if** `isElder()` return `true` and the parameter is `false`.
  * In GlowElderGuardian:
    * Make `isElder()` return `true`.

### Need help?

Come chat with us on [Discord](https://discord.gg/TFJqhsC)!

### PR DESCRIPTION
**Pull request by j1o1h1n**
This picks up from #046673f by @Pr0methean to fix #968 

* code to handle `setElder` is all in `GlowGuardian`, and works for both classes
* added `ElderGuardianStore`, using the single GuardianStore for both didn't work out well
* removed call to setElder in `Store.load`
* tests for setElder

### CODE REVIEW

File: src/main/java/net/glowstone/io/entity/ElderGuardianStore.java [hunk 1]
```diff
@@ -0,0 +1,24 @@
...
+
+    @Override
+    public void load(GlowElderGuardian entity, CompoundTag compound) {
+        super.load(entity, compound);
+    }
+
+    @Override
+    public void save(GlowElderGuardian entity, CompoundTag compound) {
+        super.save(entity, compound);
+        compound.putBool("Elder", true);
```
Comment (aramperes) [inline src/main/java/net/glowstone/io/entity/ElderGuardianStore.java]: The `Elder` tag has been removed from both `guardian` and `elder_guardian` stores, so it is no longer necessary to save it.

**Review by aramperes — CHANGES_REQUESTED** [review]
Excellent work! Just one little change before merging.

**Comment by aramperes** [comment]
Hey @j1o1h1n, apologies for the delay. Could you merge this repo's `dev` branch back into your fork's `guardian_968` branch? We've pushed a fix for the compilation errors.

**Review by aramperes — APPROVED** [review]

**Comment by aramperes** [comment]
Thanks for your contribution!
